In [1]:
import pandas as pd
import numpy as np

In [12]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
import xgboost as xgb

In [13]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

In [2]:
dataset = pd.read_csv('feature_engineered_data.csv')

In [3]:
dataset.head()

AT      AP      AH    AFDP    GTEP     TIT     TAT     TEY     CDP  \
0  4.5878  1018.7  83.675  3.5758  23.979  1086.2  549.83  134.67  11.898   
1  4.2932  1018.3  84.235  3.5709  23.951  1086.1  550.05  134.67  11.892   
2  3.9045  1018.4  84.858  3.5828  23.990  1086.5  550.19  135.10  12.042   
3  3.7436  1018.3  85.434  3.5808  23.911  1086.5  550.17  135.03  11.990   
4  3.7516  1017.8  85.182  3.5781  23.917  1085.9  550.00  134.67  11.910   

   CLUSTER  
0        1  
1        1  
2        1  
3        1  
4        1

In [4]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 68214 entries, 0 to 68213
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   AT       68214 non-null  float64
 1   AP       68214 non-null  float64
 2   AH       68214 non-null  float64
 3   AFDP     68214 non-null  float64
 4   GTEP     68214 non-null  float64
 5   TIT      68214 non-null  float64
 6   TAT      68214 non-null  float64
 7   TEY      68214 non-null  float64
 8   CDP      68214 non-null  float64
 9   CLUSTER  68214 non-null  int64  
dtypes: float64(9), int64(1)
memory usage: 5.2 MB


In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(dataset.drop(['CLUSTER'],axis=1),dataset['CLUSTER'],test_size=0.1,random_state=0)

## Selecting features using DecisonTree FeatureModelling

In [8]:
independent_features = list(dataset.columns)
independent_features.remove('CLUSTER')
print(independent_features)

['AT', 'AP', 'AH', 'AFDP', 'GTEP', 'TIT', 'TAT', 'TEY', 'CDP']


In [9]:
mylist = []
def printSubsequences(arr, index, subarr): 
        
    if index == len(arr): 
            
        if len(subarr) != 0: 
            mylist.append(subarr)
        
    else: 
        printSubsequences(arr, index + 1, subarr) 
            
        printSubsequences(arr, index + 1,  
                            subarr+[arr[index]]) 
        
    return
            
arr = independent_features 
    
printSubsequences(arr, 0, []) 

In [10]:
for lists in mylist:
    print(lists)

['CDP']
['TEY']
['TEY', 'CDP']
['TAT']
['TAT', 'CDP']
['TAT', 'TEY']
['TAT', 'TEY', 'CDP']
['TIT']
['TIT', 'CDP']
['TIT', 'TEY']
['TIT', 'TEY', 'CDP']
['TIT', 'TAT']
['TIT', 'TAT', 'CDP']
['TIT', 'TAT', 'TEY']
['TIT', 'TAT', 'TEY', 'CDP']
['GTEP']
['GTEP', 'CDP']
['GTEP', 'TEY']
['GTEP', 'TEY', 'CDP']
['GTEP', 'TAT']
['GTEP', 'TAT', 'CDP']
['GTEP', 'TAT', 'TEY']
['GTEP', 'TAT', 'TEY', 'CDP']
['GTEP', 'TIT']
['GTEP', 'TIT', 'CDP']
['GTEP', 'TIT', 'TEY']
['GTEP', 'TIT', 'TEY', 'CDP']
['GTEP', 'TIT', 'TAT']
['GTEP', 'TIT', 'TAT', 'CDP']
['GTEP', 'TIT', 'TAT', 'TEY']
['GTEP', 'TIT', 'TAT', 'TEY', 'CDP']
['AFDP']
['AFDP', 'CDP']
['AFDP', 'TEY']
['AFDP', 'TEY', 'CDP']
['AFDP', 'TAT']
['AFDP', 'TAT', 'CDP']
['AFDP', 'TAT', 'TEY']
['AFDP', 'TAT', 'TEY', 'CDP']
['AFDP', 'TIT']
['AFDP', 'TIT', 'CDP']
['AFDP', 'TIT', 'TEY']
['AFDP', 'TIT', 'TEY', 'CDP']
['AFDP', 'TIT', 'TAT']
['AFDP', 'TIT', 'TAT', 'CDP']
['AFDP', 'TIT', 'TAT', 'TEY']
['AFDP', 'TIT', 'TAT', 'TEY', 'CDP']
['AFDP', 'GTEP']
['AFDP',

In [11]:
len(mylist)

511

In [14]:
def best_features_model(features,x_train,x_test,y_train,y_test):
    model = DecisionTreeClassifier()
    model.fit(x_train,y_train)
    predictions = model.predict(x_test)
    acc = accuracy_score(y_test,predictions)
    cm = confusion_matrix(y_test,predictions)
    this_list = [acc,cm]
    return this_list,features

In [16]:
result = []
result2 = []

count = 0
for lists in mylist:
    outs1,outs2 = best_features_model(lists,X_train[lists],X_test[lists],y_train,y_test)
    result.append(outs1)
    result2.append(outs2)
    count += 1
    
    print(count)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277


In [18]:
print(result[0][0])

0.6908531222515392


In [21]:
minimum = max(result,key=lambda X:X[0])
print(minimum)
min_index = result.index(minimum)
print(result2[min_index])

[0.9186455584872472, array([[2001,  244,   13],
       [ 177, 1997,   78],
       [  10,   33, 2269]], dtype=int64)]
['AT', 'AP', 'AH', 'AFDP', 'GTEP', 'TIT', 'TAT', 'CDP']


## Selecting features based on output

In [26]:
selected_features = ['AT', 'AP', 'AH', 'AFDP', 'GTEP', 'TIT', 'TAT', 'CDP','CLUSTER']

In [27]:
df = dataset[selected_features]

In [28]:
df.head()

AT      AP      AH    AFDP    GTEP     TIT     TAT     CDP  CLUSTER
0  4.5878  1018.7  83.675  3.5758  23.979  1086.2  549.83  11.898        1
1  4.2932  1018.3  84.235  3.5709  23.951  1086.1  550.05  11.892        1
2  3.9045  1018.4  84.858  3.5828  23.990  1086.5  550.19  12.042        1
3  3.7436  1018.3  85.434  3.5808  23.911  1086.5  550.17  11.990        1
4  3.7516  1017.8  85.182  3.5781  23.917  1085.9  550.00  11.910        1

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 68214 entries, 0 to 68213
Data columns (total 9 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   AT       68214 non-null  float64
 1   AP       68214 non-null  float64
 2   AH       68214 non-null  float64
 3   AFDP     68214 non-null  float64
 4   GTEP     68214 non-null  float64
 5   TIT      68214 non-null  float64
 6   TAT      68214 non-null  float64
 7   CDP      68214 non-null  float64
 8   CLUSTER  68214 non-null  int64  
dtypes: float64(8), int64(1)
memory usage: 4.7 MB


In [30]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.drop(['CLUSTER'],axis=1),df['CLUSTER'],test_size=0.2,random_state=0)

## Model Building

In [75]:
model = GradientBoostingClassifier()

In [76]:
model.fit(X_train,y_train)

GradientBoostingClassifier()

In [77]:
model.score(X_train,y_train)

0.8764728518810357

In [78]:
predictions=model.predict(X_test)

## Evaluate Model

In [79]:
cm=confusion_matrix(y_test,predictions)
acc = accuracy_score(y_test,predictions)
print(cm)
print(acc)

[[3692  688   37]
 [ 509 3712  257]
 [  68  196 4484]]
0.8713626035329473


In [80]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       0.86      0.84      0.85      4417
           1       0.81      0.83      0.82      4478
           2       0.94      0.94      0.94      4748

    accuracy                           0.87     13643
   macro avg       0.87      0.87      0.87     13643
weighted avg       0.87      0.87      0.87     13643



## Save model

In [81]:
import pickle

In [82]:
filename = 'gb_fmodel.pkl'

In [83]:
pickle.dump(model,open(filename,'wb'))