In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('feature_selected_data.csv')

In [3]:
data.head()

AT     TAT     TEY  CLUSTER
0  4.5878  549.83  134.67        1
1  4.2932  550.05  134.67        1
2  3.9045  550.19  135.10        1
3  3.7436  550.17  135.03        1
4  3.7516  550.00  134.67        1

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 68214 entries, 0 to 68213
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   AT       68214 non-null  float64
 1   TAT      68214 non-null  float64
 2   TEY      68214 non-null  float64
 3   CLUSTER  68214 non-null  int64  
dtypes: float64(3), int64(1)
memory usage: 2.1 MB


In [5]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(data.drop(['CLUSTER'],axis=1),data['CLUSTER'],test_size=0.2,random_state=0)

In [6]:
X_train.shape,y_train.shape

((54571, 3), (54571,))

## Build Model

In [41]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
import xgboost as xgb

In [64]:
model = xgb.XGBClassifier()

In [65]:
model.fit(X_train,y_train)

c:\users\samrat\appdata\local\programs\python\python38\lib\site-packages\xgboost\sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[20:14:47] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=2, num_parallel_tree=1,
              objective='multi:softprob', random_state=0, reg_alpha=0,
              reg_lambda=1, scale_pos_weight=None, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [66]:
model.score(X_train,y_train)

0.8845357424272966

In [67]:
predictions=model.predict(X_test)

## Evaluating the model

In [68]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

In [69]:
cm=confusion_matrix(y_test,predictions)
acc = accuracy_score(y_test,predictions)
print(cm)
print(acc)

[[3633  746   38]
 [ 711 3552  215]
 [  32  225 4491]]
0.8558234992303746


In [70]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       0.83      0.82      0.83      4417
           1       0.79      0.79      0.79      4478
           2       0.95      0.95      0.95      4748

    accuracy                           0.86     13643
   macro avg       0.85      0.85      0.85     13643
weighted avg       0.86      0.86      0.86     13643



## Save the models

In [71]:
import pickle

In [72]:
filename = 'xgboost_model.pkl'

In [73]:
pickle.dump(model, open(filename, 'wb'))